version: '3'
    
services:
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      container_name: faux_investigator_server
      volumes:
        - .:/code
      ports:
        - "8000:8000"
