# Generated by Django 2.1.5 on 2020-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='barely_true',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='false',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='half_true',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='mostly_true',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='pants_on_fire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='true',
            field=models.FloatField(default=0.0),
        ),
    ]
